spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?createDatabaseIfNotExist=true
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver
    jpa:
        hibernate:
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    security:
        user:
            name: amitosh
            password: 123456
            roles: ADMIN, USER


security:
    oauth2:
        client:
            client-id: mobile
            client-secret: pin
            access-token-validity-seconds: 3600
            authorized-grant-types: refresh_token, authorization_code, password, client_credentials
            scope: READ, WRITE
